#!/usr/bin/env python
# -*- coding: utf-8 -*-

from optparse import OptionParser
import os
from time import time
import datetime



__author__ = "Raony Guimarães"
__copyright__ = "Copyright 2011, The Exome Pipeline"
__credits__ = ["Raony Guimarães"]
__license__ = "GPL"
__version__ = "1.0.1"
__maintainer__ = "Raony Guimarães"
__email__ = "raonyguimaraes@gmail.com"
__status__ = "Production"
		
#run example
#python gatk.py -i alignment/exome.sorted.bam

parser = OptionParser()

parser.add_option("-a", dest="annovar_file",
                  help="CSV Generated by annovar", metavar="ANN")
parser.add_option("-v", dest="vcf_file",
                  help="VCF File Generated by GATK", metavar="VCF")
parser.add_option("-o", dest="out_vcf_filename",
                  help="Output VCF File", metavar="VCF")
(options, args) = parser.parse_args()

annovar_file=options.annovar_file
vcf_file=options.vcf_file
out_vcf_filename=options.out_vcf_filename


#get header from VCF File
command """grep "^#" %s > %s.vcf """ % (vcf_file, out_vcf_filename)
os.system(command)

#open annovar file
ann_file = open(annovar_file, 'r')

